FROM --platform=${TARGETPLATFORM} golang:latest as builder

ARG CGO_ENABLED=0

COPY ./ /root/src/
WORKDIR /root/src/
ARG VERSION=""
RUN set -eux; \
    file_ver=$(tr -d '\r\n' < .version 2>/dev/null || true); \
    base=${VERSION:-${file_ver:-$(git describe --tags --abbrev=0 || echo dev)}}; \
    v="$base"; \
    go build -ldflags "-s -w -X main.version=$v" -trimpath -o mosdns


FROM --platform=${TARGETPLATFORM} alpine:latest

COPY --from=builder /root/src/mosdns /usr/bin/

RUN apk add --no-cache ca-certificates
