# 文件用途:
# - 构建“主分流入口服务” `sequence_main`，并监听本机 `127.0.0.1:5656`。
# 依赖关系:
# - `config.yaml` 主入口（53 端口）会转发到该入口。
# 说明:
# - 此层作为调用层级中的“聚合入口”，便于拆分和复用子序列。
plugins:
#把main主分流逻辑打包成一个对外服务供调用
  - tag: forward_all_in
    type: forward
    args:
      concurrent: 1
      upstreams:
        - addr: "udp://127.0.0.1:5656"

#主分流服务器
  - tag: udp_main
    type: udp_server
    args:
      entry: sequence_main
      listen: 127.0.0.1:5656

  - tag: tcp_main
    type: tcp_server
    args:
      entry: sequence_main
      listen: 127.0.0.1:5656
      idle_timeout: 720
