plugins:
# 定义了一个带过期缓存的内部使用/外部使用的国内dns服务器
  - tag: domestic
    type: aliapi
    args:
      concurrent: 3
      failure_suppress_ttl: 10
      persistent_servfail_threshold: 3
      persistent_servfail_ttl: 60
      upstream_failure_threshold: 3
      upstream_circuit_break_seconds: 60
      upstreams:
        - addr: "223.5.5.5"
        - addr: "223.6.6.6"
