plugins:
#处理非A、AAAA请求
  - tag: sequence_other
    type: sequence
    args:
      - matches: fast_mark 16
        exec: $sequence_local          #geositecn向国内dns请求
      - matches: "!fast_mark 16"
        exec: $sequence_google         #!geositecn向国外dns请求